### ISSUE TITLE
Give every object a meaningful `__repr__`

### ISSUE THREAD

**Issue by reactormonk** [skadistats/skadi#36]
`<skadi.protoc.dota_usermessages_pb2.CDOTAUserMsg_ParticleManager object at 0x14f80210>` is not too readable. Would be nice if `print()` would help inspecting the data a bit.

**Comment by onethirtyfive** [comment]
That particular `__repr__` is actually generated by the protobuf library. The ones Skadi owns aren't too good either, but I can keep that in mind for future work. Thanks for the suggestion.

For future reference, anything from `skadi.protoc` is the domain of protobuf, since it's all code generated from protobuf definitions.

**Comment by reactormonk** [comment]
FYI

```
from google.protobuf.text_format import *
PrintMessage(message, sys,stdout)
```
